<template>
  <div>
    <q-btn
        class="button"
        @click="$emit('today')"
        unelevated
        color="grey-3"
        text-color="grey-8"
    >
      <!--style="margin: 2px;"-->
      Today
    </q-btn>
    <q-btn
        no-caps
        class="button"
        @click="$emit('prev')"
        unelevated
        icon="arrow_left"
    >
      <!--Previous-->
      <!--Back-->
    </q-btn>
    <q-btn
        no-caps
        class="button"
        @click="$emit('next')"
        unelevated
        icon-right="arrow_right"
    >
      <!--Next-->
      <!--Forward-->
    </q-btn>
  </div>
</template>
<script setup lang="ts">
</script>